#!/usr/bin/env python3
"""Generate atlas-geometry.js: the flat top view of the Atlas prototype.

Reads the prototype case STLs and KiCad board from a checkout of
mwlaboratories/atlas (branch cursor/restore-built-prototype-91dd) and
writes SVG path data plus key positions in board millimetres.

    python scripts/atlas_geometry.py /path/to/atlas > atlas-geometry.js

Needs numpy and shapely. The STLs model the left half only; the right
half is the board's mirror image (switch columns 34..114 ↔ 186..266).

Layers, bottom to top:
  case   housing.stl sliced below its top fillet (walnut frame, outer extent)
  top    housing.stl sliced just under its top face (the flat wood top)
  cover  pcb-cover.stl sliced just under its top face (yellow plate:
         fills the frame's pocket and forms the thumb wing)
"""
from __future__ import annotations

import json
import re
import struct
import sys
from pathlib import Path

import numpy as np
from shapely.geometry import LineString, Polygon
from shapely.ops import polygonize, unary_union

# STL (y up) → board (KiCad, y down). Fitted on the cover's 17 key
# holes, which land on the board's switch centres to within 0.1 mm.
DX, DY = 114.0, 84.0
MIRROR_X = 300.0


def load_stl(p: Path) -> np.ndarray:
    b = p.read_bytes()
    if b[:5] == b"solid" and b"facet" in b[:400]:
        v = [list(map(float, l.split()[1:4])) for l in b.decode().splitlines()
             if l.strip().startswith("vertex")]
        return np.array(v).reshape(-1, 3, 3)
    n = struct.unpack("<I", b[80:84])[0]
    a = np.frombuffer(b[84:84 + n * 50], dtype=np.dtype(
        [("n", "<3f4"), ("v", "<9f4"), ("a", "<u2")]))
    return a["v"].reshape(-1, 3, 3).astype(float)


def section(tris: np.ndarray, z: float) -> Polygon:
    segs = []
    for t in tris:
        d = t[:, 2] - z
        pts = []
        for i in range(3):
            a, b, da, db = t[i], t[(i + 1) % 3], d[i], d[(i + 1) % 3]
            if (da < 0) != (db < 0):
                pts.append(a + (b - a) * (da / (da - db)))
        if len(pts) == 2:
            segs.append(LineString([tuple(np.round(pts[0][:2], 4)),
                                    tuple(np.round(pts[1][:2], 4))]))
    polys = sorted(polygonize(unary_union(segs)), key=lambda p: -p.area)
    return Polygon(polys[0].exterior)


def to_board(poly: Polygon) -> list[tuple[float, float]]:
    poly = poly.simplify(0.05, preserve_topology=True)
    return [(round(x + DX, 2), round(DY - y, 2)) for x, y in poly.exterior.coords[:-1]]


def path(pts, mirror=False) -> str:
    f = (lambda x: round(MIRROR_X - x, 2)) if mirror else (lambda x: x)
    return "M" + "L".join(f"{f(x):g} {y:g}" for x, y in pts) + "Z"


def switches(pcb: Path):
    text = pcb.read_text()
    out = []
    for m in re.finditer(r'\(footprint "[^"]*Choc[^"]*"(.*?)\n\t\)', text, re.S):
        at = re.search(r'\(at ([\d.\-]+) ([\d.\-]+)(?: ([\d.\-]+))?\)', m.group(1))
        x, y, r = float(at[1]), float(at[2]), float(at[3] or 0)
        out.append((x, y, -r + 0.0))  # KiCad rotates counter-clockwise, SVG clockwise
    return out


def main(root: Path) -> None:
    stl = root / "stl"
    housing = load_stl(stl / "housing.stl")
    cover = load_stl(stl / "pcb-cover.stl")
    zh = housing[:, :, 2].max()
    zc = cover[:, :, 2].max()
    layers = {
        "case": to_board(section(housing, zh - 2.0)),
        "top": to_board(section(housing, zh - 0.1)),
        "cover": to_board(section(cover, zc - 0.5)),
    }
    # Trackpoint: the 5 mm round hole in the cover.
    hole = next(Polygon(h) for h in unary_union(
        [Polygon(t[:, :2]).buffer(1e-4) for t in cover]).buffer(-1e-4).interiors
        if 18 < Polygon(h).area < 21)
    tp = (round(hole.centroid.x + DX, 2), round(DY - hole.centroid.y, 2))

    keys = sorted(switches(root / "pcb/atlas/atlas.kicad_pcb"), key=lambda k: (k[1] > 95, k[0], k[1]))
    geo = {
        "source": "mwlaboratories/atlas@cursor/restore-built-prototype-91dd",
        "mirrorX": MIRROR_X,
        "left": {k: path(v) for k, v in layers.items()},
        "right": {k: path(v, True) for k, v in layers.items()},
        "trackpoints": [tp, (round(MIRROR_X - tp[0], 2), tp[1])],
        "switches": keys,
    }
    print("// Generated by scripts/atlas_geometry.py; do not edit by hand.")
    print("export default " + json.dumps(geo, indent=1) + ";")


if __name__ == "__main__":
    main(Path(sys.argv[1] if len(sys.argv) > 1 else "../atlas"))
